### ISSUE TITLE
Cut new version with fix for missing encoding of long_description

### ISSUE THREAD

**Issue by jrbeilke** [pycontribs/python-crowd#47]
Looks like there hasn't been a new version tagged since #41 was merged and this is preventing me from installing with pip (pypi shows latest version as 1.0.1 from September 2016).
https://pypi.org/project/Crowd/#history

```
Collecting crowd>=1.0.1 (from django-crowd-auth->-r /var/www/django-app/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d9/d0/adb745e946363a66c90a844311423a859c082364a744fcb5827bab6b48c1/Crowd-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gw69epfc/crowd/setup.py", line 13, in <module>
        long_description=open(os.path.join(__dir__, 'README.rst')).read(),
      File "/var/www/django-app/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3555: ordinal not in range(128)
```

Could we get a new version pushed to pypi with this fix?

Ping @aelse as it looks like you're the only maintainer of the project on pypi currently.

**Comment by aelse** [comment]
@jrbeilke I've pushed 1.0.2 to PyPI. Sorry this has been inconvenient.
